# Generated by Django 5.0.6 on 2024-06-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioMania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='resena',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='BiblioMania.manga'),
        ),
        migrations.CreateModel(
            name='EstadoMangaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('V', 'Viendo'), ('C', 'Considerando'), ('T', 'Completado'), ('N', 'Ninguno')], max_length=1)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BiblioMania.manga')),
            ],
        ),
    ]
