# Generated by Django 5.0.6 on 2024-06-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioMania', '0002_author_alter_resena_manga_estadomangausuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Autor',
        ),
    ]
