# Generated by Django 5.0.6 on 2024-06-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioMania', '0005_alter_estadomangausuario_user_alter_resena_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='rating',
            field=models.CharField(choices=[('1', '1 estrella'), ('2', '2 estrellas'), ('3', '3 estrellas'), ('4', '4 estrellas'), ('5', '5 estrellas')], max_length=1),
        ),
    ]
