# Generated by Django 5.0.6 on 2024-06-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioMania', '0006_alter_resena_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadomangausuario',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resena',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
