# Generated by Django 5.0.6 on 2024-06-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioMania', '0010_remove_suscripcion_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='suscription_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
