# Generated by Django 5.0.6 on 2024-06-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioMania', '0011_alter_suscripcion_suscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='suscription_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
